### ISSUE TITLE
Affine transformation, Distance between images

### ISSUE THREAD

**Issue by guisf** [neurodata-papers/non-parametric-clustering#5]
- [x] 1. plot misclassification error vs n for k-means++ and k-mediods++
- [x] 2. read procrustes: https://en.wikipedia.org/wiki/Procrustes_analysis
- [ ]  3. implement canonical error k-means++ (affine image transformation to canonical coordinates, followed by squared error)

**Comment by jovo** [comment]
- 3. punting until better understanding of kmeans for frobenius metric
