### ISSUE TITLE
shape 

### ISSUE THREAD

**Issue by jovo** [neurodata-papers/non-parametric-clustering#9]
- [x] procrustes in kmeans
- [x] generate shape simulation
- [x] make plot axes tight
- [x] learn about munkres
- [x] read theory k-means 2 papers

**Comment by guisf** [comment]
Implemented K-means and K-medoids with arbitrary distance function. For the MNIST dataset:
1. simple Euclidean metric performs way better. Without digit 1 we get about 5% error, with digit 1 we get 20% error. Procrustes without digit 1 get about 25% error.

**Comment by guisf** [comment]
http://nbviewer.jupyter.org/github/neurodata/non-parametric-clustering/blob/master/shape_clustering.ipynb

**Comment by guisf** [comment]
Moved the reading 2 papers for next week. Can we close this?
@jovo
